import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { ApplicationError } from '../../common/errors/application-error.js';
import { AttachmentStorage } from '../../infrastructure/storage/attachment-storage.js';
import { createAuthenticate, requirePermission } from '../auth/auth-context.js';
import type { AuthRepository } from '../auth/auth-repository.js';
import type { TokenService } from '../auth/token-service.js';
import type { PayablesRepository, PaymentEligibleInstallmentFilters, PaymentInput, PaymentListFilters, RecurrenceCancellationInput, RecurrenceGenerationInput, RecurrenceInput, RecurrenceListFilters, RecurrenceRevisionInput, TitleInput, XmlImportGenerateInput, XmlImportInput, XmlImportListFilters } from './payables-repository.js';

interface Options { authRepository:AuthRepository;tokenService:TokenService;repository:PayablesRepository;attachmentStorageRoot:string }
const uuid=z.uuid();const money=z.number().finite().positive();const nonnegative=z.number().finite().min(0);
const installment=z.object({installmentNumber:z.number().int().min(1),installmentCount:z.number().int().min(1),amount:money,dueDate:z.iso.date(),paymentMethodId:uuid,notes:z.string().max(5000).nullable().optional()}).refine(v=>v.installmentNumber<=v.installmentCount,{message:'Installment number cannot exceed count'});
const title=z.object({supplierId:uuid,categoryId:uuid,documentTypeId:uuid,paymentTermId:uuid.nullable().optional(),costCenterId:uuid.nullable().optional(),documentNumber:z.string().trim().min(1).max(80),documentSeries:z.string().trim().max(30).nullable().optional(),description:z.string().trim().min(1).max(255),originCode:z.enum(['MANUAL','XML','INTEGRATION']).optional(),issueDate:z.iso.date(),originalAmount:money,discountAmount:nonnegative.optional(),additionalAmount:nonnegative.optional(),notes:z.string().max(5000).nullable().optional(),draft:z.boolean().optional(),duplicateConfirmed:z.boolean().optional(),installments:z.array(installment).min(1).max(360)}) satisfies z.ZodType<TitleInput>;
const titleUpdate=z.object({supplierId:uuid.optional(),categoryId:uuid.optional(),documentTypeId:uuid.optional(),paymentTermId:uuid.nullable().optional(),costCenterId:uuid.nullable().optional(),documentNumber:z.string().trim().min(1).max(80).optional(),documentSeries:z.string().trim().max(30).nullable().optional(),description:z.string().trim().min(1).max(255).optional(),issueDate:z.iso.date().optional(),originalAmount:money.optional(),discountAmount:nonnegative.optional(),additionalAmount:nonnegative.optional(),notes:z.string().max(5000).nullable().optional()});
const id=z.object({id:uuid});const titleId=z.object({titleId:uuid});const paymentId=z.object({paymentId:uuid});
const list=z.object({page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20),search:z.string().trim().min(1).max(100).optional(),status:z.string().trim().max(40).toUpperCase().optional(),dueFrom:z.iso.date().optional(),dueTo:z.iso.date().optional(),supplierId:uuid.optional(),categoryId:uuid.optional()});
const eligibleInstallmentsList=z.object({page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20),search:z.string().trim().min(1).max(100).optional(),status:z.enum(['OPEN','OVERDUE','PARTIALLY_PAID']).optional(),dueFrom:z.iso.date().optional(),dueTo:z.iso.date().optional(),supplierId:uuid.optional(),companyId:uuid.optional()}) satisfies z.ZodType<{page:number;pageSize:number}&PaymentEligibleInstallmentFilters>;
const paymentsList=z.object({page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20),search:z.string().trim().min(1).max(100).optional(),status:z.enum(['EFFECTIVE','REVERSED']).optional(),paidFrom:z.iso.date().optional(),paidTo:z.iso.date().optional(),supplierId:uuid.optional(),companyId:uuid.optional()}) satisfies z.ZodType<{page:number;pageSize:number}&PaymentListFilters>;
const xmlList=z.object({page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20),search:z.string().trim().min(1).max(120).optional(),status:z.string().trim().max(40).toUpperCase().optional(),dueFrom:z.iso.date().optional(),dueTo:z.iso.date().optional(),supplierId:uuid.optional(),recipientKind:z.enum(['MAIN','BRANCH','UNKNOWN']).optional(),recipientDocumentNumber:z.string().trim().min(1).max(32).optional(),importedFrom:z.iso.date().optional(),importedTo:z.iso.date().optional()}) satisfies z.ZodType<{page:number;pageSize:number}&XmlImportListFilters>;
const recurrenceList=z.object({page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20),search:z.string().trim().min(1).max(120).optional(),status:z.enum(['ACTIVE','SUSPENDED','CANCELLED','FINISHED']).optional(),companyId:uuid.optional(),supplierId:uuid.optional(),frequencyCode:z.enum(['WEEKLY','BIWEEKLY','MONTHLY','ANNUAL']).optional()}) satisfies z.ZodType<{page:number;pageSize:number}&RecurrenceListFilters>;
const recurrenceBase=z.object({companyId:uuid,supplierId:uuid,categoryId:uuid,costCenterId:uuid.nullable().optional(),documentTypeId:uuid,paymentMethodId:uuid,paymentTermId:uuid.nullable().optional(),description:z.string().trim().min(1).max(255),baseDocumentNumber:z.string().trim().max(80).nullable().optional(),baseAmount:money,frequencyCode:z.enum(['WEEKLY','BIWEEKLY','MONTHLY','ANNUAL']),startDate:z.iso.date(),endDate:z.iso.date().nullable().optional(),maxOccurrences:z.number().int().min(1).nullable().optional(),dueDay:z.number().int().min(1).max(31).nullable().optional(),isOpenEnded:z.boolean().optional(),notes:z.string().max(5000).nullable().optional()});
const recurrenceRules=(v:Partial<RecurrenceInput>,ctx:z.RefinementCtx)=>{if(v.frequencyCode&&(v.frequencyCode==='MONTHLY'||v.frequencyCode==='ANNUAL')&&!v.dueDay)ctx.addIssue({code:'custom',path:['dueDay'],message:'Dia de vencimento é obrigatório para recorrência mensal/anual.'});if(v.endDate&&v.startDate&&v.endDate<v.startDate)ctx.addIssue({code:'custom',path:['endDate'],message:'Data final não pode ser anterior à data inicial.'});};
const normalizeRecurrencePayload=(value:unknown):unknown=>{
  if(!value||typeof value!=='object'||Array.isArray(value))return value;
  const data={...(value as Record<string,unknown>)};
  if(data.endDate==='')data.endDate=null;
  if(data.maxOccurrences==='')data.maxOccurrences=null;
  if(data.dueDay==='')data.dueDay=null;
  if(data.costCenterId==='')data.costCenterId=null;
  if(data.paymentTermId==='')data.paymentTermId=null;
  if(data.baseDocumentNumber==='')data.baseDocumentNumber=null;
  if(data.notes==='')data.notes=null;
  return data;
};
const recurrence=z.preprocess(normalizeRecurrencePayload,recurrenceBase).superRefine((v,ctx)=>{if(!v.isOpenEnded&&!v.endDate&&!v.maxOccurrences)ctx.addIssue({code:'custom',path:['endDate'],message:'Informe data final, quantidade de ocorrências ou confirme recorrência sem prazo final.'});if(v.isOpenEnded&&(v.endDate||v.maxOccurrences))ctx.addIssue({code:'custom',path:['isOpenEnded'],message:'Recorrência sem prazo final não pode informar data final ou quantidade máxima.'});recurrenceRules(v,ctx);}) satisfies z.ZodType<RecurrenceInput>;
const recurrenceUpdate=z.preprocess(normalizeRecurrencePayload,recurrenceBase.partial()).refine((data)=>Object.keys(data as Record<string,unknown>).length>0,'At least one field is required').superRefine((v,ctx)=>{if(v.isOpenEnded&&(v.endDate||v.maxOccurrences))ctx.addIssue({code:'custom',path:['isOpenEnded'],message:'Recorrência sem prazo final não pode informar data final ou quantidade máxima.'});recurrenceRules(v,ctx);}) satisfies z.ZodType<Partial<RecurrenceInput>>;
const recurrenceGeneration=z.object({untilDate:z.iso.date().nullable().optional(),occurrenceCount:z.number().int().min(1).max(366).nullable().optional()}).refine(v=>v.untilDate||v.occurrenceCount,{message:'untilDate or occurrenceCount is required'}) satisfies z.ZodType<RecurrenceGenerationInput>;
const recurrenceCancellation=z.object({reason:z.string().trim().min(3).max(1000),cancelFutureTitles:z.boolean().optional()}) satisfies z.ZodType<RecurrenceCancellationInput>;
const recurrenceRevision=z.preprocess(normalizeRecurrencePayload,recurrenceBase.partial().extend({effectiveDate:z.iso.date(),reason:z.string().trim().min(3).max(1000),cancelFutureTitles:z.boolean().optional()})).superRefine((v,ctx)=>{if(v.isOpenEnded&&(v.endDate||v.maxOccurrences))ctx.addIssue({code:'custom',path:['isOpenEnded'],message:'Recorrência sem prazo final não pode informar data final ou quantidade máxima.'});recurrenceRules(v,ctx);}) satisfies z.ZodType<RecurrenceRevisionInput>;
const xmlInstallment=z.object({installmentNumber:z.number().int().min(1),dueDate:z.iso.date(),amount:money,paymentMethodRaw:z.string().trim().max(120).nullable().optional(),notes:z.string().max(1000).nullable().optional()});
const xmlImport=z.object({accessKey:z.string().trim().regex(/^\d{44}$/).nullable().optional(),attachmentId:uuid.nullable().optional(),rawXml:z.string().min(1).nullable().optional(),sourceFileName:z.string().trim().max(255).nullable().optional(),sourceMimeType:z.string().trim().max(120).nullable().optional(),sourceSizeBytes:z.number().int().positive().nullable().optional(),sourceFileHash:z.string().trim().min(32).max(128).nullable().optional(),supplierLegalName:z.string().trim().max(255).nullable().optional(),supplierTradeName:z.string().trim().max(255).nullable().optional(),supplierDocumentNumber:z.string().trim().max(32).nullable().optional(),supplierStateRegistration:z.string().trim().max(32).nullable().optional(),supplierCityName:z.string().trim().max(120).nullable().optional(),supplierStateCode:z.string().trim().length(2).nullable().optional(),recipientLegalName:z.string().trim().max(255).nullable().optional(),recipientDocumentNumber:z.string().trim().max(32).nullable().optional(),recipientStateRegistration:z.string().trim().max(32).nullable().optional(),recipientCityName:z.string().trim().max(120).nullable().optional(),recipientStateCode:z.string().trim().length(2).nullable().optional(),recipientKind:z.enum(['MAIN','BRANCH','UNKNOWN']).optional(),mainCompanyDocumentNumber:z.string().trim().max(32).nullable().optional(),documentModel:z.string().trim().max(10).nullable().optional(),documentNumber:z.string().trim().max(80).nullable().optional(),documentSeries:z.string().trim().max(30).nullable().optional(),issueDate:z.iso.date().nullable().optional(),operationDate:z.iso.date().nullable().optional(),dueDate:z.iso.date().nullable().optional(),productsAmount:nonnegative.nullable().optional(),freightAmount:nonnegative.nullable().optional(),insuranceAmount:nonnegative.nullable().optional(),discountAmount:nonnegative.nullable().optional(),otherAmount:nonnegative.nullable().optional(),invoiceTotalAmount:nonnegative.nullable().optional(),paymentAmount:nonnegative.nullable().optional(),currencyCode:z.string().trim().length(3).optional(),parsedData:z.record(z.string(),z.unknown()).optional(),installments:z.array(xmlInstallment).max(120).optional()}).refine(v=>v.attachmentId||v.rawXml,{message:'attachmentId or rawXml is required'}) satisfies z.ZodType<XmlImportInput>;
const xmlImportGenerate=z.object({categoryId:uuid.nullable().optional(),documentTypeId:uuid.nullable().optional(),paymentMethodId:uuid.nullable().optional(),paymentTermId:uuid.nullable().optional(),costCenterId:uuid.nullable().optional(),description:z.string().trim().min(1).max(255).nullable().optional(),duplicateConfirmed:z.boolean().optional()}) satisfies z.ZodType<XmlImportGenerateInput>;
function parse<T>(schema:z.ZodType<T>,value:unknown):T{const result=schema.safeParse(value);if(!result.success)throw new ApplicationError({code:'VALIDATION_ERROR',message:'Invalid request data',statusCode:400,details:result.error.issues.map(i=>({path:i.path.join('.'),message:i.message}))});return result.data;}
function user(request:FastifyRequest):string{return request.authUser!.id;}

export function payablesRoutes(app:FastifyInstance,o:Options):Promise<void>{
 const auth=createAuthenticate(o.authRepository,o.tokenService);const view=requirePermission('PAYABLE_TITLE_VIEW');
 const create=requirePermission('PAYABLE_TITLE_CREATE');const update=requirePermission('PAYABLE_TITLE_UPDATE');
 const cancel=requirePermission('PAYABLE_TITLE_CANCEL');const approve=requirePermission('PAYABLE_TITLE_APPROVE');
 const pay=requirePermission('PAYMENT_CREATE');const reverse=requirePermission('PAYMENT_REVERSE');const batch=requirePermission('PAYMENT_BATCH_MANAGE');
 const tag=requirePermission('PAYABLE_TAG_MANAGE');const attachment=requirePermission('PAYABLE_ATTACHMENT_MANAGE');const xml=requirePermission('XML_IMPORT_MANAGE');
 const recurrenceView=requirePermission('RECURRENCE_VIEW');const recurrenceCreate=requirePermission('RECURRENCE_CREATE');
 const recurrenceUpdatePermission=requirePermission('RECURRENCE_UPDATE');const recurrenceCancel=requirePermission('RECURRENCE_CANCEL');
 const recurrenceGenerate=requirePermission('RECURRENCE_GENERATE');
 const storage=new AttachmentStorage(o.attachmentStorageRoot);
 app.get('/recurrences',{preHandler:[auth,recurrenceView]},async req=>{const q=parse(recurrenceList,req.query);return o.repository.listRecurrences(q.page,q.pageSize,{search:q.search,status:q.status,companyId:q.companyId,supplierId:q.supplierId,frequencyCode:q.frequencyCode});});
 app.get('/recurrences/:id',{preHandler:[auth,recurrenceView]},async req=>{const entity=await o.repository.getRecurrence(parse(id,req.params).id);if(!entity)throw new ApplicationError({code:'RESOURCE_NOT_FOUND',message:'Recurrence not found',statusCode:404});return entity;});
 app.get('/recurrences/:id/titles',{preHandler:[auth,recurrenceView]},async req=>o.repository.listRecurrenceTitles(parse(id,req.params).id));
 app.get('/recurrences/:id/cancellation-preview',{preHandler:[auth,recurrenceView]},async req=>{const q=parse(z.object({effectiveDate:z.iso.date().optional()}),req.query);return o.repository.previewRecurrenceCancellation(parse(id,req.params).id,user(req),q.effectiveDate);});
 app.post('/recurrences',{preHandler:[auth,recurrenceCreate]},async(req,reply)=>reply.status(201).send(await o.repository.createRecurrence(parse(recurrence,req.body),user(req))));
 app.patch('/recurrences/:id',{preHandler:[auth,recurrenceUpdatePermission]},async req=>o.repository.updateRecurrence(parse(id,req.params).id,parse(recurrenceUpdate,req.body),user(req)));
 app.post('/recurrences/:id/suspend',{preHandler:[auth,recurrenceCancel]},async req=>{const body=parse(z.object({reason:z.string().trim().min(3).max(1000).nullable().optional()}),req.body??{});return o.repository.changeRecurrenceStatus(parse(id,req.params).id,'SUSPENDED',user(req),body.reason);});
 app.post('/recurrences/:id/reactivate',{preHandler:[auth,recurrenceCancel]},async req=>o.repository.changeRecurrenceStatus(parse(id,req.params).id,'ACTIVE',user(req)));
 app.post('/recurrences/:id/cancel',{preHandler:[auth,recurrenceCancel]},async req=>o.repository.cancelRecurrence(parse(id,req.params).id,parse(recurrenceCancellation,req.body),user(req)));
 app.post('/recurrences/:id/revise',{preHandler:[auth,recurrenceUpdatePermission]},async req=>o.repository.reviseRecurrenceFromDate(parse(id,req.params).id,parse(recurrenceRevision,req.body),user(req)));
 app.post('/recurrences/:id/preview-generation',{preHandler:[auth,recurrenceGenerate]},async req=>o.repository.previewRecurrenceGeneration(parse(id,req.params).id,parse(recurrenceGeneration,req.body),user(req)));
 app.post('/recurrences/:id/generate',{preHandler:[auth,recurrenceGenerate]},async(req,reply)=>reply.status(201).send(await o.repository.generateRecurrenceTitles(parse(id,req.params).id,parse(recurrenceGeneration,req.body),user(req))));
 app.get('/payables',{preHandler:[auth,view]},async req=>{const q=parse(list,req.query);return o.repository.list(q.page,q.pageSize,{search:q.search,status:q.status,dueFrom:q.dueFrom,dueTo:q.dueTo,supplierId:q.supplierId,categoryId:q.categoryId});});
 app.get('/payables/duplicates',{preHandler:[auth,view]},async req=>{const q=parse(z.object({supplierId:uuid,documentNumber:z.string().min(1),documentSeries:z.string().nullable().optional(),installmentNumber:z.coerce.number().int().min(1).optional()}),req.query);return o.repository.duplicates(q.supplierId,q.documentNumber,q.documentSeries??null,q.installmentNumber);});
 app.get('/payables/:id',{preHandler:[auth,view]},async req=>{const entity=await o.repository.get(parse(id,req.params).id);if(!entity)throw new ApplicationError({code:'RESOURCE_NOT_FOUND',message:'Title not found',statusCode:404});return entity;});
 app.post('/payables',{preHandler:[auth,create]},async(req,reply)=>reply.status(201).send(await o.repository.create(parse(title,req.body),user(req))));
 app.patch('/payables/:id',{preHandler:[auth,update]},async req=>o.repository.updateTitle(parse(id,req.params).id,parse(titleUpdate,req.body),user(req)));
 app.patch('/payable-installments/:id',{preHandler:[auth,update]},async req=>{const p=parse(id,req.params);const b=parse(z.object({amount:money,dueDate:z.iso.date(),paymentMethodId:uuid}),req.body);return o.repository.updateInstallment(p.id,b.amount,b.dueDate,b.paymentMethodId,user(req));});
 app.post('/payables/:id/cancel',{preHandler:[auth,cancel]},async(req,reply)=>{const p=parse(id,req.params);const b=parse(z.object({reason:z.string().trim().min(3).max(1000)}),req.body);await o.repository.cancelTitle(p.id,b.reason,user(req));return reply.status(204).send();});

 app.post('/payables/:titleId/tags',{preHandler:[auth,tag]},async(req,reply)=>{const p=parse(titleId,req.params);const b=parse(z.object({tagId:uuid.optional(),name:z.string().trim().min(1).max(80).optional()}).refine(v=>v.tagId||v.name),req.body);let tagId=b.tagId;
   if(!tagId){const rows=await o.repository.execute(`INSERT INTO financeiro.tags(name,created_by,updated_by) VALUES($1,$2,$2) ON CONFLICT(name) DO UPDATE SET name=EXCLUDED.name RETURNING id`,[b.name,user(req)]);tagId=(rows[0] as {id:string}).id;}
   await o.repository.execute(`INSERT INTO financeiro.payable_title_tags(payable_title_id,tag_id,created_by) VALUES($1,$2,$3) ON CONFLICT DO NOTHING`,[p.titleId,tagId,user(req)]);await o.repository.record('PAYABLE_TITLE',p.titleId,'TAG_LINKED',user(req),{tagId});return reply.status(201).send({tagId});});
 app.delete('/payables/:titleId/tags/:id',{preHandler:[auth,tag]},async(req,reply)=>{const p=parse(z.object({titleId:uuid,id:uuid}),req.params);await o.repository.execute(`DELETE FROM financeiro.payable_title_tags WHERE payable_title_id=$1 AND tag_id=$2`,[p.titleId,p.id]);await o.repository.record('PAYABLE_TITLE',p.titleId,'TAG_UNLINKED',user(req),{tagId:p.id});return reply.status(204).send();});
 app.post('/payables/:titleId/attachments',{preHandler:[auth,attachment]},async(req,reply)=>{const p=parse(titleId,req.params);const b=parse(z.object({attachmentTypeId:uuid,originalName:z.string().min(1).max(255),storedName:z.string().min(1).max(255),relativePath:z.string().min(1).max(500),mimeType:z.string().min(1).max(120),sizeBytes:z.number().int().positive(),fileHash:z.string().min(32).max(128)}),req.body);const entity=await o.repository.executeOne(`INSERT INTO financeiro.attachments(payable_title_id,attachment_type_id,original_name,stored_name,relative_path,mime_type,size_bytes,file_hash,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[p.titleId,b.attachmentTypeId,b.originalName,b.storedName,b.relativePath,b.mimeType,b.sizeBytes,b.fileHash,user(req)]);await o.repository.record('ATTACHMENT',(entity as {id:string}).id,'CREATED',user(req),entity);return reply.status(201).send(entity);});
 app.delete('/attachments/:id',{preHandler:[auth,attachment]},async(req,reply)=>{const p=parse(id,req.params);await o.repository.executeOne(`UPDATE financeiro.attachments SET deleted_at=CURRENT_TIMESTAMP,deleted_by=$2 WHERE id=$1 AND deleted_at IS NULL RETURNING id`,[p.id,user(req)]);await o.repository.record('ATTACHMENT',p.id,'DEACTIVATED',user(req),{});return reply.status(204).send();});
 app.get('/attachments/:id/download',{preHandler:[auth,view]},async(req,reply)=>{const entity=await o.repository.getAttachment(parse(id,req.params).id) as {originalName:string;relativePath:string;mimeType:string;sizeBytes:string|number}|null;if(!entity)throw new ApplicationError({code:'RESOURCE_NOT_FOUND',message:'Attachment not found',statusCode:404});const safeName=entity.originalName.replace(/["\r\n]/g,'_');return reply.header('Content-Type',entity.mimeType).header('Content-Length',String(entity.sizeBytes)).header('Content-Disposition',`attachment; filename="${safeName}"; filename*=UTF-8''${encodeURIComponent(entity.originalName)}`).send(storage.stream(entity.relativePath));});

 app.post('/payables/:titleId/approvals',{preHandler:[auth,approve]},async(req,reply)=>{const p=parse(titleId,req.params);const b=parse(z.object({approvalLevel:z.number().int().min(1),approverId:uuid}),req.body);const entity=await o.repository.executeOne(`INSERT INTO financeiro.approvals(payable_title_id,approval_level,approver_id,status_id,created_by,updated_by) VALUES($1,$2,$3,(SELECT id FROM financeiro.approval_statuses WHERE code='PENDING'),$4,$4) RETURNING *`,[p.titleId,b.approvalLevel,b.approverId,user(req)]);await o.repository.execute(`UPDATE financeiro.payable_titles SET status_id=(SELECT id FROM financeiro.payable_title_statuses WHERE code='IN_APPROVAL'),updated_by=$2 WHERE id=$1`,[p.titleId,user(req)]);await o.repository.record('APPROVAL',(entity as {id:string}).id,'CREATED',user(req),entity);return reply.status(201).send(entity);});
 app.post('/approvals/:id/decision',{preHandler:[auth,approve]},async(req)=>{const p=parse(id,req.params);const b=parse(z.object({decision:z.enum(['APPROVED','REJECTED','RETURNED']),reason:z.string().max(1000).nullable().optional()}),req.body);const entity=await o.repository.executeOne(`UPDATE financeiro.approvals SET status_id=(SELECT id FROM financeiro.approval_statuses WHERE code=$2),reason=$3,decided_at=CURRENT_TIMESTAMP,updated_by=$4 WHERE id=$1 AND approver_id=$4 RETURNING *`,[p.id,b.decision,b.reason??null,user(req)]);const titleStatus={APPROVED:'APPROVED',REJECTED:'REJECTED',RETURNED:'DRAFT'}[b.decision];await o.repository.execute(`UPDATE financeiro.payable_titles SET status_id=(SELECT id FROM financeiro.payable_title_statuses WHERE code=$2),updated_by=$3 WHERE id=$1`,[(entity as {payableTitleId:string}).payableTitleId,titleStatus,user(req)]);await o.repository.record('APPROVAL',p.id,b.decision,user(req),entity);return entity;});

 const payment=z.object({installmentId:uuid,batchId:uuid.nullable().optional(),bankAccountId:uuid,paymentMethodId:uuid,paymentDate:z.iso.date(),principalAmount:money,interestAmount:nonnegative.optional(),penaltyAmount:nonnegative.optional(),discountAmount:nonnegative.optional(),additionalAmount:nonnegative.optional(),transactionNumber:z.string().max(100).nullable().optional(),overpaymentConfirmed:z.boolean().optional()})
   .refine(v=>v.principalAmount+(v.interestAmount??0)+(v.penaltyAmount??0)+(v.additionalAmount??0)-(v.discountAmount??0)>0,{message:'Payment movement amount must be greater than zero'}) satisfies z.ZodType<PaymentInput>;
 app.get('/payable-installments/eligible-for-payment',{preHandler:[auth,view]},async req=>{const q=parse(eligibleInstallmentsList,req.query);return o.repository.listPaymentEligibleInstallments(q.page,q.pageSize,{search:q.search,status:q.status,dueFrom:q.dueFrom,dueTo:q.dueTo,supplierId:q.supplierId,companyId:q.companyId});});
 app.get('/payments',{preHandler:[auth,view]},async req=>{const q=parse(paymentsList,req.query);return o.repository.listPayments(q.page,q.pageSize,{search:q.search,status:q.status,paidFrom:q.paidFrom,paidTo:q.paidTo,supplierId:q.supplierId,companyId:q.companyId});});
 app.get('/payments/:paymentId',{preHandler:[auth,view]},async req=>{const entity=await o.repository.getPayment(parse(paymentId,req.params).paymentId);if(!entity)throw new ApplicationError({code:'RESOURCE_NOT_FOUND',message:'Payment not found',statusCode:404});return entity;});
 app.post('/payments',{preHandler:[auth,pay]},async(req,reply)=>reply.status(201).send(await o.repository.addPayment(parse(payment,req.body),user(req))));
 app.post('/payments/:paymentId/attachments',{preHandler:[auth,attachment]},async(req,reply)=>{const p=parse(paymentId,req.params);const file=await req.file();if(!file)throw new ApplicationError({code:'ATTACHMENT_REQUIRED',message:'Attachment file is required',statusCode:400});const saved=await storage.savePaymentReceipt(p.paymentId,{filename:file.filename,mimetype:file.mimetype,file:file.file});try{return reply.status(201).send(await o.repository.addPaymentAttachment(p.paymentId,saved,user(req)));}catch(error){await storage.delete(saved.relativePath);throw error;}});
 app.post('/payments/:paymentId/reverse',{preHandler:[auth,reverse]},async(req,reply)=>{const p=parse(paymentId,req.params);const b=parse(z.object({reason:z.string().trim().min(3).max(1000)}),req.body);return reply.status(201).send(await o.repository.reversePayment(p.paymentId,b.reason,user(req)));});
 app.post('/payment-batches',{preHandler:[auth,batch]},async(req,reply)=>{const b=parse(z.object({batchCode:z.string().min(1).max(40),bankAccountId:uuid,scheduledDate:z.iso.date(),notes:z.string().max(5000).nullable().optional()}),req.body);const entity=await o.repository.executeOne(`INSERT INTO financeiro.payment_batches(batch_code,bank_account_id,scheduled_date,status_id,notes,created_by,updated_by) VALUES($1,$2,$3,(SELECT id FROM financeiro.payment_batch_statuses WHERE code='OPEN'),$4,$5,$5) RETURNING *`,[b.batchCode,b.bankAccountId,b.scheduledDate,b.notes??null,user(req)]);await o.repository.record('PAYMENT_BATCH',(entity as {id:string}).id,'CREATED',user(req),entity);return reply.status(201).send(entity);});
 app.get('/payment-batches',{preHandler:[auth,view]},async()=>o.repository.execute(`SELECT b.*,s.code status_code FROM financeiro.payment_batches b JOIN financeiro.payment_batch_statuses s ON s.id=b.status_id ORDER BY scheduled_date DESC`));
 app.post('/xml-imports',{preHandler:[auth,xml]},async(req,reply)=>reply.status(201).send(await o.repository.createXmlImport(parse(xmlImport,req.body),user(req))));
 app.post('/xml-imports/:id/generate-payable',{preHandler:[auth,create]},async(req,reply)=>reply.status(201).send(await o.repository.generatePayableFromXml(parse(id,req.params).id,parse(xmlImportGenerate,req.body),user(req))));
 app.get('/xml-imports',{preHandler:[auth,view]},async req=>{const q=parse(xmlList,req.query);return o.repository.listXmlImports(q.page,q.pageSize,{search:q.search,status:q.status,dueFrom:q.dueFrom,dueTo:q.dueTo,supplierId:q.supplierId,recipientKind:q.recipientKind,recipientDocumentNumber:q.recipientDocumentNumber,importedFrom:q.importedFrom,importedTo:q.importedTo});});
 app.get('/xml-imports/:id',{preHandler:[auth,view]},async req=>{const entity=await o.repository.getXmlImport(parse(id,req.params).id);if(!entity)throw new ApplicationError({code:'RESOURCE_NOT_FOUND',message:'XML import not found',statusCode:404});return entity;});
 app.post('/xml-imports/:id/reprocess',{preHandler:[auth,xml]},async req=>o.repository.reprocessXmlImport(parse(id,req.params).id,user(req)));
 app.delete('/xml-imports/:id',{preHandler:[auth,xml]},async(req,reply)=>{await o.repository.deleteXmlImport(parse(id,req.params).id,user(req));return reply.status(204).send();});
 return Promise.resolve();
}
