import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { ApplicationError } from '../../common/errors/application-error.js';
import { createAuthenticate, requirePermission } from '../auth/auth-context.js';
import type { AuthRepository } from '../auth/auth-repository.js';
import type { TokenService } from '../auth/token-service.js';
import type { PayablesRepository, TitleInput, XmlImportInput } from './payables-repository.js';

interface Options { authRepository:AuthRepository;tokenService:TokenService;repository:PayablesRepository }
const uuid=z.uuid();const money=z.number().finite().positive();const nonnegative=z.number().finite().min(0);
const installment=z.object({installmentNumber:z.number().int().min(1),installmentCount:z.number().int().min(1),amount:money,dueDate:z.iso.date(),paymentMethodId:uuid,notes:z.string().max(5000).nullable().optional()}).refine(v=>v.installmentNumber<=v.installmentCount,{message:'Installment number cannot exceed count'});
const title=z.object({supplierId:uuid,categoryId:uuid,documentTypeId:uuid,paymentTermId:uuid.nullable().optional(),costCenterId:uuid.nullable().optional(),documentNumber:z.string().trim().min(1).max(80),documentSeries:z.string().trim().max(30).nullable().optional(),description:z.string().trim().min(1).max(255),originCode:z.enum(['MANUAL','XML','INTEGRATION']).optional(),issueDate:z.iso.date(),originalAmount:money,discountAmount:nonnegative.optional(),additionalAmount:nonnegative.optional(),notes:z.string().max(5000).nullable().optional(),draft:z.boolean().optional(),duplicateConfirmed:z.boolean().optional(),installments:z.array(installment).min(1).max(360)}) satisfies z.ZodType<TitleInput>;
const titleUpdate=z.object({supplierId:uuid.optional(),categoryId:uuid.optional(),documentTypeId:uuid.optional(),paymentTermId:uuid.nullable().optional(),costCenterId:uuid.nullable().optional(),documentNumber:z.string().trim().min(1).max(80).optional(),documentSeries:z.string().trim().max(30).nullable().optional(),description:z.string().trim().min(1).max(255).optional(),issueDate:z.iso.date().optional(),originalAmount:money.optional(),discountAmount:nonnegative.optional(),additionalAmount:nonnegative.optional(),notes:z.string().max(5000).nullable().optional()});
const id=z.object({id:uuid});const titleId=z.object({titleId:uuid});const paymentId=z.object({paymentId:uuid});
const list=z.object({page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20),search:z.string().trim().min(1).max(100).optional(),status:z.string().trim().max(40).toUpperCase().optional(),dueFrom:z.iso.date().optional(),dueTo:z.iso.date().optional(),supplierId:uuid.optional(),categoryId:uuid.optional()});
const xmlInstallment=z.object({installmentNumber:z.number().int().min(1),dueDate:z.iso.date(),amount:money,paymentMethodRaw:z.string().trim().max(120).nullable().optional(),notes:z.string().max(1000).nullable().optional()});
const xmlImport=z.object({accessKey:z.string().trim().max(60).nullable().optional(),attachmentId:uuid.nullable().optional(),rawXml:z.string().min(1).nullable().optional(),sourceFileName:z.string().trim().max(255).nullable().optional(),sourceMimeType:z.string().trim().max(120).nullable().optional(),sourceSizeBytes:z.number().int().positive().nullable().optional(),sourceFileHash:z.string().trim().min(32).max(128).nullable().optional(),supplierLegalName:z.string().trim().max(255).nullable().optional(),supplierTradeName:z.string().trim().max(255).nullable().optional(),supplierDocumentNumber:z.string().trim().max(32).nullable().optional(),supplierStateRegistration:z.string().trim().max(32).nullable().optional(),supplierCityName:z.string().trim().max(120).nullable().optional(),supplierStateCode:z.string().trim().length(2).nullable().optional(),documentModel:z.string().trim().max(10).nullable().optional(),documentNumber:z.string().trim().max(80).nullable().optional(),documentSeries:z.string().trim().max(30).nullable().optional(),issueDate:z.iso.date().nullable().optional(),operationDate:z.iso.date().nullable().optional(),dueDate:z.iso.date().nullable().optional(),productsAmount:nonnegative.nullable().optional(),freightAmount:nonnegative.nullable().optional(),insuranceAmount:nonnegative.nullable().optional(),discountAmount:nonnegative.nullable().optional(),otherAmount:nonnegative.nullable().optional(),invoiceTotalAmount:nonnegative.nullable().optional(),paymentAmount:nonnegative.nullable().optional(),currencyCode:z.string().trim().length(3).optional(),parsedData:z.record(z.string(),z.unknown()).optional(),installments:z.array(xmlInstallment).max(120).optional()}).refine(v=>v.attachmentId||v.rawXml,{message:'attachmentId or rawXml is required'}) satisfies z.ZodType<XmlImportInput>;
function parse<T>(schema:z.ZodType<T>,value:unknown):T{const result=schema.safeParse(value);if(!result.success)throw new ApplicationError({code:'VALIDATION_ERROR',message:'Invalid request data',statusCode:400,details:result.error.issues.map(i=>({path:i.path.join('.'),message:i.message}))});return result.data;}
function user(request:FastifyRequest):string{return request.authUser!.id;}

export function payablesRoutes(app:FastifyInstance,o:Options):Promise<void>{
 const auth=createAuthenticate(o.authRepository,o.tokenService);const view=requirePermission('PAYABLE_TITLE_VIEW');
 const create=requirePermission('PAYABLE_TITLE_CREATE');const update=requirePermission('PAYABLE_TITLE_UPDATE');
 const cancel=requirePermission('PAYABLE_TITLE_CANCEL');const approve=requirePermission('PAYABLE_TITLE_APPROVE');
 const pay=requirePermission('PAYMENT_CREATE');const reverse=requirePermission('PAYMENT_REVERSE');const batch=requirePermission('PAYMENT_BATCH_MANAGE');
 const tag=requirePermission('PAYABLE_TAG_MANAGE');const attachment=requirePermission('PAYABLE_ATTACHMENT_MANAGE');const xml=requirePermission('XML_IMPORT_MANAGE');
 app.get('/payables',{preHandler:[auth,view]},async req=>{const q=parse(list,req.query);return o.repository.list(q.page,q.pageSize,{search:q.search,status:q.status,dueFrom:q.dueFrom,dueTo:q.dueTo,supplierId:q.supplierId,categoryId:q.categoryId});});
 app.get('/payables/duplicates',{preHandler:[auth,view]},async req=>{const q=parse(z.object({supplierId:uuid,documentNumber:z.string().min(1),documentSeries:z.string().nullable().optional(),installmentNumber:z.coerce.number().int().min(1).optional()}),req.query);return o.repository.duplicates(q.supplierId,q.documentNumber,q.documentSeries??null,q.installmentNumber);});
 app.get('/payables/:id',{preHandler:[auth,view]},async req=>{const entity=await o.repository.get(parse(id,req.params).id);if(!entity)throw new ApplicationError({code:'RESOURCE_NOT_FOUND',message:'Title not found',statusCode:404});return entity;});
 app.post('/payables',{preHandler:[auth,create]},async(req,reply)=>reply.status(201).send(await o.repository.create(parse(title,req.body),user(req))));
 app.patch('/payables/:id',{preHandler:[auth,update]},async req=>o.repository.updateTitle(parse(id,req.params).id,parse(titleUpdate,req.body),user(req)));
 app.patch('/payable-installments/:id',{preHandler:[auth,update]},async req=>{const p=parse(id,req.params);const b=parse(z.object({amount:money,dueDate:z.iso.date(),paymentMethodId:uuid}),req.body);return o.repository.updateInstallment(p.id,b.amount,b.dueDate,b.paymentMethodId,user(req));});
 app.post('/payables/:id/cancel',{preHandler:[auth,cancel]},async(req,reply)=>{const p=parse(id,req.params);const b=parse(z.object({reason:z.string().trim().min(3).max(1000)}),req.body);await o.repository.cancelTitle(p.id,b.reason,user(req));return reply.status(204).send();});

 app.post('/payables/:titleId/tags',{preHandler:[auth,tag]},async(req,reply)=>{const p=parse(titleId,req.params);const b=parse(z.object({tagId:uuid.optional(),name:z.string().trim().min(1).max(80).optional()}).refine(v=>v.tagId||v.name),req.body);let tagId=b.tagId;
   if(!tagId){const rows=await o.repository.execute(`INSERT INTO financeiro.tags(name,created_by,updated_by) VALUES($1,$2,$2) ON CONFLICT(name) DO UPDATE SET name=EXCLUDED.name RETURNING id`,[b.name,user(req)]);tagId=(rows[0] as {id:string}).id;}
   await o.repository.execute(`INSERT INTO financeiro.payable_title_tags(payable_title_id,tag_id,created_by) VALUES($1,$2,$3) ON CONFLICT DO NOTHING`,[p.titleId,tagId,user(req)]);await o.repository.record('PAYABLE_TITLE',p.titleId,'TAG_LINKED',user(req),{tagId});return reply.status(201).send({tagId});});
 app.delete('/payables/:titleId/tags/:id',{preHandler:[auth,tag]},async(req,reply)=>{const p=parse(z.object({titleId:uuid,id:uuid}),req.params);await o.repository.execute(`DELETE FROM financeiro.payable_title_tags WHERE payable_title_id=$1 AND tag_id=$2`,[p.titleId,p.id]);await o.repository.record('PAYABLE_TITLE',p.titleId,'TAG_UNLINKED',user(req),{tagId:p.id});return reply.status(204).send();});
 app.post('/payables/:titleId/attachments',{preHandler:[auth,attachment]},async(req,reply)=>{const p=parse(titleId,req.params);const b=parse(z.object({attachmentTypeId:uuid,originalName:z.string().min(1).max(255),storedName:z.string().min(1).max(255),relativePath:z.string().min(1).max(500),mimeType:z.string().min(1).max(120),sizeBytes:z.number().int().positive(),fileHash:z.string().min(32).max(128)}),req.body);const entity=await o.repository.executeOne(`INSERT INTO financeiro.attachments(payable_title_id,attachment_type_id,original_name,stored_name,relative_path,mime_type,size_bytes,file_hash,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[p.titleId,b.attachmentTypeId,b.originalName,b.storedName,b.relativePath,b.mimeType,b.sizeBytes,b.fileHash,user(req)]);await o.repository.record('ATTACHMENT',(entity as {id:string}).id,'CREATED',user(req),entity);return reply.status(201).send(entity);});
 app.delete('/attachments/:id',{preHandler:[auth,attachment]},async(req,reply)=>{const p=parse(id,req.params);await o.repository.executeOne(`UPDATE financeiro.attachments SET deleted_at=CURRENT_TIMESTAMP,deleted_by=$2 WHERE id=$1 AND deleted_at IS NULL RETURNING id`,[p.id,user(req)]);await o.repository.record('ATTACHMENT',p.id,'DEACTIVATED',user(req),{});return reply.status(204).send();});

 app.post('/payables/:titleId/approvals',{preHandler:[auth,approve]},async(req,reply)=>{const p=parse(titleId,req.params);const b=parse(z.object({approvalLevel:z.number().int().min(1),approverId:uuid}),req.body);const entity=await o.repository.executeOne(`INSERT INTO financeiro.approvals(payable_title_id,approval_level,approver_id,status_id,created_by,updated_by) VALUES($1,$2,$3,(SELECT id FROM financeiro.approval_statuses WHERE code='PENDING'),$4,$4) RETURNING *`,[p.titleId,b.approvalLevel,b.approverId,user(req)]);await o.repository.execute(`UPDATE financeiro.payable_titles SET status_id=(SELECT id FROM financeiro.payable_title_statuses WHERE code='IN_APPROVAL'),updated_by=$2 WHERE id=$1`,[p.titleId,user(req)]);await o.repository.record('APPROVAL',(entity as {id:string}).id,'CREATED',user(req),entity);return reply.status(201).send(entity);});
 app.post('/approvals/:id/decision',{preHandler:[auth,approve]},async(req)=>{const p=parse(id,req.params);const b=parse(z.object({decision:z.enum(['APPROVED','REJECTED','RETURNED']),reason:z.string().max(1000).nullable().optional()}),req.body);const entity=await o.repository.executeOne(`UPDATE financeiro.approvals SET status_id=(SELECT id FROM financeiro.approval_statuses WHERE code=$2),reason=$3,decided_at=CURRENT_TIMESTAMP,updated_by=$4 WHERE id=$1 AND approver_id=$4 RETURNING *`,[p.id,b.decision,b.reason??null,user(req)]);const titleStatus={APPROVED:'APPROVED',REJECTED:'REJECTED',RETURNED:'DRAFT'}[b.decision];await o.repository.execute(`UPDATE financeiro.payable_titles SET status_id=(SELECT id FROM financeiro.payable_title_statuses WHERE code=$2),updated_by=$3 WHERE id=$1`,[(entity as {payableTitleId:string}).payableTitleId,titleStatus,user(req)]);await o.repository.record('APPROVAL',p.id,b.decision,user(req),entity);return entity;});

 const payment=z.object({installmentId:uuid,batchId:uuid.nullable().optional(),bankAccountId:uuid,paymentMethodId:uuid,paymentDate:z.iso.date(),principalAmount:money,interestAmount:nonnegative.optional(),penaltyAmount:nonnegative.optional(),discountAmount:nonnegative.optional(),additionalAmount:nonnegative.optional(),transactionNumber:z.string().max(100).nullable().optional(),overpaymentConfirmed:z.boolean().optional()});
 app.post('/payments',{preHandler:[auth,pay]},async(req,reply)=>reply.status(201).send(await o.repository.addPayment(parse(payment,req.body),user(req))));
 app.post('/payments/:paymentId/reverse',{preHandler:[auth,reverse]},async(req,reply)=>{const p=parse(paymentId,req.params);const b=parse(z.object({reason:z.string().trim().min(3).max(1000)}),req.body);return reply.status(201).send(await o.repository.reversePayment(p.paymentId,b.reason,user(req)));});
 app.post('/payment-batches',{preHandler:[auth,batch]},async(req,reply)=>{const b=parse(z.object({batchCode:z.string().min(1).max(40),bankAccountId:uuid,scheduledDate:z.iso.date(),notes:z.string().max(5000).nullable().optional()}),req.body);const entity=await o.repository.executeOne(`INSERT INTO financeiro.payment_batches(batch_code,bank_account_id,scheduled_date,status_id,notes,created_by,updated_by) VALUES($1,$2,$3,(SELECT id FROM financeiro.payment_batch_statuses WHERE code='OPEN'),$4,$5,$5) RETURNING *`,[b.batchCode,b.bankAccountId,b.scheduledDate,b.notes??null,user(req)]);await o.repository.record('PAYMENT_BATCH',(entity as {id:string}).id,'CREATED',user(req),entity);return reply.status(201).send(entity);});
 app.get('/payment-batches',{preHandler:[auth,view]},async()=>o.repository.execute(`SELECT b.*,s.code status_code FROM financeiro.payment_batches b JOIN financeiro.payment_batch_statuses s ON s.id=b.status_id ORDER BY scheduled_date DESC`));
 app.post('/xml-imports',{preHandler:[auth,xml]},async(req,reply)=>reply.status(201).send(await o.repository.createXmlImport(parse(xmlImport,req.body),user(req))));
 app.get('/xml-imports',{preHandler:[auth,view]},async()=>o.repository.execute(`SELECT x.*,s.code status_code FROM financeiro.xml_imports x JOIN financeiro.xml_import_statuses s ON s.id=x.status_id ORDER BY imported_at DESC`));
 return Promise.resolve();
}
