import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState, type FormEvent, type ReactElement } from 'react';
import { ApiError, httpClient } from '../api/http-client';
import { useAuth } from '../auth/auth-context';
import { Breadcrumb } from '../components/ui/breadcrumb';
import { Button } from '../components/ui/button';
import { Card } from '../components/ui/card';

interface Certificate { id:string;companyId:string;companyName:string;displayName:string;originalFileName:string;fingerprintSha256:string;serialNumber:string;subjectName:string;issuerName:string;certificateDocumentNumber:string|null;validFrom:string;validUntil:string;daysUntilExpiration:number;status:'VALID'|'EXPIRING'|'EXPIRED';isActive:boolean;lastValidatedAt:string }
interface CertificateList { data:Certificate[] }
const date=(value:string):string=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short'}).format(new Date(value));
const error=(value:unknown):string|undefined=>value instanceof ApiError?value.message:value?'Não foi possível concluir a operação.':undefined;

export function DigitalCertificatesPage():ReactElement{
  const {session}=useAuth();const client=useQueryClient();const companies=session?.user.companies??[];
  const [open,setOpen]=useState(false);const [companyId,setCompanyId]=useState(session?.user.defaultCompanyId??companies[0]?.id??'');const [name,setName]=useState('');const [password,setPassword]=useState('');const [file,setFile]=useState<File|null>(null);
  const certificates=useQuery({queryKey:['digital-certificates'],queryFn:async()=>(await httpClient.get<CertificateList>('/api/v1/digital-certificates')).data});
  const save=useMutation({mutationFn:async():Promise<Certificate>=>{if(!file)throw new Error('Selecione o arquivo do certificado.');const data=new FormData();data.set('companyId',companyId);data.set('displayName',name);data.set('password',password);data.set('certificate',file);return (await httpClient.post<Certificate>('/api/v1/digital-certificates',data)).data;},onSuccess:async()=>{setOpen(false);setName('');setPassword('');setFile(null);await client.invalidateQueries({queryKey:['digital-certificates']});}});
  const validate=useMutation({mutationFn:async(id:string):Promise<Certificate>=>(await httpClient.post<Certificate>(`/api/v1/digital-certificates/${id}/validate`)).data,onSuccess:async()=>{await client.invalidateQueries({queryKey:['digital-certificates']});}});
  const remove=useMutation({mutationFn:async(id:string):Promise<void>=>{await httpClient.delete(`/api/v1/digital-certificates/${id}`);},onSuccess:async()=>{await client.invalidateQueries({queryKey:['digital-certificates']});}});
  const message=error(save.error)??error(validate.error)??error(remove.error);
  function submit(event:FormEvent):void{event.preventDefault();save.mutate();}
  return <div className="grid gap-6">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><Breadcrumb items={[{label:'Configurações'},{label:'Certificados digitais'}]}/><h1 className="mt-3 text-3xl font-black tracking-tight text-slate-950">Certificados digitais</h1><p className="mt-2 max-w-3xl text-slate-600">Gerencie certificados A1 usados pelas integrações fiscais de cada empresa.</p></div><Button onClick={()=>setOpen(true)}>+ Cadastrar certificado</Button></header>
    <section className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><strong>Credencial crítica.</strong> O arquivo e a senha são criptografados no servidor e nunca ficam disponíveis para download. Substitua o certificado antes do vencimento.</section>
    {message?<p role="alert" className="rounded-2xl bg-red-50 p-4 text-sm font-semibold text-red-700">{message}</p>:null}
    {open?<Card><form className="grid gap-4 md:grid-cols-2" onSubmit={submit}><div><label className="mb-1 block text-sm font-bold">Empresa</label><select className="min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3" value={companyId} onChange={e=>setCompanyId(e.target.value)} required>{companies.map(c=><option key={c.id} value={c.id}>{c.tradeName||c.legalName} · {c.documentNumber}</option>)}</select></div><div><label className="mb-1 block text-sm font-bold">Identificação</label><input className="min-h-11 w-full rounded-xl border border-slate-300 px-3" value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: A1 Produção 2026"/></div><div><label className="mb-1 block text-sm font-bold">Arquivo A1</label><input className="min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2" type="file" accept=".pfx,.p12,application/x-pkcs12" onChange={e=>setFile(e.target.files?.[0]??null)} required/></div><div><label className="mb-1 block text-sm font-bold">Senha do certificado</label><input className="min-h-11 w-full rounded-xl border border-slate-300 px-3" type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} required/></div><div className="flex justify-end gap-2 md:col-span-2"><Button variant="secondary" onClick={()=>setOpen(false)}>Cancelar</Button><Button type="submit" disabled={save.isPending}>{save.isPending?'Validando e protegendo...':'Salvar certificado'}</Button></div></form></Card>:null}
    <Card>{certificates.isLoading?<p className="py-10 text-center text-slate-500">Carregando certificados...</p>:certificates.isError?<p role="alert" className="py-10 text-center text-red-700">Não foi possível consultar os certificados.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-slate-200 text-slate-500"><th className="px-3 py-3">Empresa / certificado</th><th className="px-3 py-3">Validade</th><th className="px-3 py-3">Situação</th><th className="px-3 py-3">Impressão digital</th><th className="px-3 py-3 text-right">Ações</th></tr></thead><tbody>{certificates.data?.data.map(item=><tr key={item.id} className="border-b border-slate-100 last:border-0"><td className="px-3 py-3"><strong className="block text-slate-950">{item.companyName}</strong><span className="text-slate-500">{item.displayName}</span></td><td className="whitespace-nowrap px-3 py-3">{date(item.validUntil)}<span className="block text-xs text-slate-500">{item.daysUntilExpiration} dias</span></td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-xs font-bold ${item.status==='VALID'?'bg-emerald-50 text-emerald-700':item.status==='EXPIRING'?'bg-amber-50 text-amber-700':'bg-red-50 text-red-700'}`}>{item.status==='VALID'?'Válido':item.status==='EXPIRING'?'Vence em breve':'Vencido'}</span></td><td className="px-3 py-3"><span className="block max-w-48 truncate font-mono text-xs text-slate-500" title={item.fingerprintSha256}>{item.fingerprintSha256}</span></td><td className="whitespace-nowrap px-3 py-3 text-right"><div className="flex justify-end gap-2"><Button variant="secondary" onClick={()=>validate.mutate(item.id)} disabled={validate.isPending}>Validar</Button><Button variant="danger" onClick={()=>{if(window.confirm(`Desativar o certificado de ${item.companyName}?`))remove.mutate(item.id);}} disabled={remove.isPending}>Desativar</Button></div></td></tr>)}</tbody></table>{certificates.data?.data.length===0?<p className="py-10 text-center text-slate-500">Nenhum certificado cadastrado.</p>:null}</div>}</Card>
  </div>;
}
