/* eslint-disable @typescript-eslint/no-base-to-string */
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { UseQueryResult } from '@tanstack/react-query';
import { useEffect, useMemo, useState, type ReactElement } from 'react';
import { useFieldArray, useForm } from 'react-hook-form';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ApiError, httpClient } from '../api/http-client';
import { Button } from '../components/ui/button';
import { Card } from '../components/ui/card';
import { currency, statusLabel, type Installment, type ListResponse, type PayableDetail } from './payables-types';
import { payableTabs } from './payable-form-contract';

interface Lookup {id:string;name?:string;legalName?:string;code?:string}
interface Values {supplierId:string;categoryId:string;documentTypeId:string;paymentTermId?:string;costCenterId?:string;documentNumber:string;documentSeries?:string;description:string;issueDate:string;originalAmount:number;discountAmount:number;additionalAmount:number;notes?:string;draft:boolean;installments:Installment[]}
type Tab=typeof payableTabs[number];
const tabs=payableTabs;
function useLookup(path:string):UseQueryResult<Lookup[]>{return useQuery({queryKey:['payable-lookup',path],queryFn:async()=>{const response=await httpClient.get<ListResponse<Lookup>>(`/api/v1${path}`,{params:{pageSize:100,active:true}});return response.data.data;},staleTime:60000});}
function optionLabel(item:Lookup):string{return item.legalName??item.name??item.code??item.id;}
const inputClass='min-h-10 rounded-lg border border-slate-300 bg-white px-3 outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-100';

export function PayableFormPage():ReactElement{
  const {id}=useParams();const editing=Boolean(id);const navigate=useNavigate();const queryClient=useQueryClient();const [tab,setTab]=useState<Tab>('Dados da Conta');const [duplicatePayload,setDuplicatePayload]=useState<Values>();
  const suppliers=useLookup('/suppliers');const categories=useLookup('/financial-categories');const documentTypes=useLookup('/document-types');const methods=useLookup('/payment-methods');const terms=useLookup('/payment-terms');const costCenters=useLookup('/cost-centers');
  const detail=useQuery({queryKey:['payable',id],queryFn:async()=>{const response=await httpClient.get<PayableDetail>(`/api/v1/payables/${id}`);return response.data;},enabled:editing});
  const {register,control,handleSubmit,reset,watch,formState:{errors}}=useForm<Values>({defaultValues:{issueDate:new Date().toISOString().slice(0,10),originalAmount:0,discountAmount:0,additionalAmount:0,draft:false,installments:[{installmentNumber:1,installmentCount:1,amount:0,dueDate:'',paymentMethodId:''}]}});const installments=useFieldArray({control,name:'installments'});
  useEffect(()=>{if(detail.data)reset({supplierId:detail.data.supplierId,categoryId:detail.data.categoryId,documentTypeId:detail.data.documentTypeId,paymentTermId:detail.data.paymentTermId??'',costCenterId:detail.data.costCenterId??'',documentNumber:detail.data.documentNumber,documentSeries:detail.data.documentSeries??'',description:detail.data.description,issueDate:detail.data.issueDate.slice(0,10),originalAmount:Number(detail.data.originalAmount),discountAmount:Number(detail.data.discountAmount),additionalAmount:Number(detail.data.additionalAmount),notes:detail.data.notes??'',draft:detail.data.statusCode==='DRAFT',installments:detail.data.installments.map(item=>({...item,amount:Number(item.amount),dueDate:item.dueDate.slice(0,10)}))});},[detail.data,reset]);
  const original=watch('originalAmount')||0;const discount=watch('discountAmount')||0;const additional=watch('additionalAmount')||0;const total=useMemo(()=>Number(original)-Number(discount)+Number(additional),[original,discount,additional]);const installmentValues=watch('installments');const installmentTotal=installmentValues.reduce((sum,item)=>sum+Number(item.amount||0),0);
  const mutation=useMutation({mutationFn:async({values,confirmed=false}:{values:Values;confirmed?:boolean})=>{if(editing){await httpClient.patch(`/api/v1/payables/${id}`,{supplierId:values.supplierId,categoryId:values.categoryId,documentTypeId:values.documentTypeId,paymentTermId:values.paymentTermId||null,costCenterId:values.costCenterId||null,documentNumber:values.documentNumber,documentSeries:values.documentSeries||null,description:values.description,issueDate:values.issueDate,originalAmount:values.originalAmount,discountAmount:values.discountAmount,additionalAmount:values.additionalAmount,notes:values.notes||null});for(const item of values.installments)if(item.id)await httpClient.patch(`/api/v1/payable-installments/${item.id}`,{amount:item.amount,dueDate:item.dueDate,paymentMethodId:item.paymentMethodId});return id;}
      const response=await httpClient.post<{id:string}>('/api/v1/payables',{...values,paymentTermId:values.paymentTermId||null,costCenterId:values.costCenterId||null,documentSeries:values.documentSeries||null,notes:values.notes||null,duplicateConfirmed:confirmed});return response.data.id;},onSuccess:async savedId=>{setDuplicatePayload(undefined);await queryClient.invalidateQueries({queryKey:['payables']});await navigate(`/payables/${savedId}`,{replace:true});},onError:(error,variables)=>{if(error instanceof ApiError&&error.code==='POSSIBLE_DUPLICATE')setDuplicatePayload(variables.values);}});
  const submit=handleSubmit(async values=>{if(Math.round(installmentTotal*100)!==Math.round(total*100)){setTab('Parcelas');return;}await mutation.mutateAsync({values}).catch(()=>undefined);});
  const cancelTitle=async():Promise<void>=>{if(!id)return;const reason=window.prompt('Informe a justificativa do cancelamento:');if(!reason)return;await httpClient.post(`/api/v1/payables/${id}/cancel`,{reason});await queryClient.invalidateQueries({queryKey:['payables']});await navigate('/payables');};
  if(editing&&detail.isLoading)return <p className="py-20 text-center text-slate-500">Carregando título…</p>;
  return <form className="grid gap-6" onSubmit={event=>void submit(event)}><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Link to="/payables" className="text-sm font-semibold text-teal-700 hover:underline">← Contas a pagar</Link><h1 className="mt-2 text-3xl font-bold">{editing?'Editar conta':'Nova conta a pagar'}</h1>{detail.data&&<p className="mt-2 text-sm text-slate-600">{detail.data.documentNumber} • {statusLabel(detail.data.statusCode)}</p>}</div><div className="flex flex-wrap gap-2">{editing&&detail.data?.statusCode!=='CANCELLED'&&<Button type="button" variant="danger" onClick={()=>void cancelTitle()}>Cancelar título</Button>}<Button type="button" variant="secondary" onClick={()=>void navigate('/payables')}>Voltar</Button><Button type="submit" disabled={mutation.isPending}>{mutation.isPending?'Salvando…':'Salvar'}</Button></div></header><div className="flex gap-1 overflow-x-auto border-b border-slate-200">{tabs.map(item=><button key={item} type="button" onClick={()=>setTab(item)} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-semibold ${tab===item?'border-teal-700 text-teal-800':'border-transparent text-slate-500 hover:text-slate-800'}`}>{item}</button>)}</div>
  {tab==='Dados da Conta'&&<Card><div className="grid gap-5 md:grid-cols-2"><Select label="Fornecedor" required items={suppliers.data} registration={register('supplierId',{required:true})}/><Select label="Categoria" required items={categories.data} registration={register('categoryId',{required:true})}/><label className="grid gap-1.5 text-sm font-medium">Descrição / Histórico<input className={inputClass} {...register('description',{required:true})}/></label><label className="grid gap-1.5 text-sm font-medium">Número do Documento<input className={inputClass} {...register('documentNumber',{required:true})}/></label><Select label="Tipo de Documento" required items={documentTypes.data} registration={register('documentTypeId',{required:true})}/><label className="grid gap-1.5 text-sm font-medium">Série<input className={inputClass} {...register('documentSeries')}/></label><label className="grid gap-1.5 text-sm font-medium">Data de Emissão<input type="date" className={inputClass} {...register('issueDate',{required:true})}/></label><Select label="Condição de Pagamento" items={terms.data} registration={register('paymentTermId')}/><label className="grid gap-1.5 text-sm font-medium">Valor Original<input type="number" step="0.01" min="0.01" className={inputClass} {...register('originalAmount',{valueAsNumber:true,required:true,min:0.01})}/></label><label className="grid gap-1.5 text-sm font-medium">Desconto<input type="number" step="0.01" min="0" className={inputClass} {...register('discountAmount',{valueAsNumber:true,min:0})}/></label><label className="grid gap-1.5 text-sm font-medium">Acréscimo<input type="number" step="0.01" min="0" className={inputClass} {...register('additionalAmount',{valueAsNumber:true,min:0})}/></label><div className="rounded-xl bg-teal-50 p-4"><p className="text-sm font-semibold text-teal-800">Valor Total</p><p className="mt-1 text-2xl font-bold text-teal-950">{currency(total)}</p><p className="mt-1 text-xs text-teal-700">Calculado automaticamente</p></div></div>{Object.keys(errors).length>0&&<p className="mt-5 text-sm text-red-700">Revise os campos obrigatórios.</p>}</Card>}
  {tab==='Parcelas'&&<Card><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-bold">Parcelas</h2><p className="text-sm text-slate-600">A soma deve ser igual a {currency(total)}.</p></div>{!editing&&<Button type="button" variant="secondary" onClick={()=>installments.append({installmentNumber:installments.fields.length+1,installmentCount:installments.fields.length+1,amount:0,dueDate:'',paymentMethodId:''})}>Adicionar parcela</Button>}</div><div className="grid gap-4">{installments.fields.map((field,index)=><div key={field.id} className="grid gap-3 rounded-xl border border-slate-200 p-4 md:grid-cols-[100px_130px_1fr_1fr_auto]"><label className="grid gap-1 text-xs font-semibold">Parcela<input readOnly className={inputClass} {...register(`installments.${index}.installmentNumber`,{valueAsNumber:true})}/></label><label className="grid gap-1 text-xs font-semibold">Total<input className={inputClass} {...register(`installments.${index}.installmentCount`,{valueAsNumber:true,min:1})}/></label><label className="grid gap-1 text-xs font-semibold">Valor<input type="number" step="0.01" min="0.01" className={inputClass} {...register(`installments.${index}.amount`,{valueAsNumber:true,required:true})}/></label><label className="grid gap-1 text-xs font-semibold">Vencimento<input type="date" className={inputClass} {...register(`installments.${index}.dueDate`,{required:true})}/></label><div className="md:col-span-2"><Select label="Forma de Pagamento" required items={methods.data} registration={register(`installments.${index}.paymentMethodId`,{required:true})}/></div>{!editing&&installments.fields.length>1&&<button type="button" className="self-end text-sm font-semibold text-red-700" onClick={()=>installments.remove(index)}>Remover</button>}</div>)}</div><div className={`mt-5 rounded-lg p-3 text-sm font-semibold ${Math.round(installmentTotal*100)===Math.round(total*100)?'bg-emerald-50 text-emerald-800':'bg-red-50 text-red-800'}`}>Total das parcelas: {currency(installmentTotal)} {Math.round(installmentTotal*100)!==Math.round(total*100)&&'— ajuste necessário'}</div></Card>}
  {tab==='Impostos'&&<Card><Empty title="Impostos" text="As regras de impostos e retenções permanecem pendentes de decisão funcional. Nenhum valor fiscal será presumido nesta etapa."/></Card>}
  {tab==='Aprovações'&&<Card>{detail.data?.approvals.length?<div className="grid gap-3">{detail.data.approvals.map((item,index)=><div key={index} className="rounded-lg border border-slate-200 p-4 text-sm">Nível {String(item.approvalLevel??'—')} • {statusLabel(String(item.statusCode??'PENDING'))}</div>)}</div>:<Empty title="Aprovações" text={editing?'Nenhuma aprovação registrada para este título.':'Salve o título antes de iniciar o fluxo de aprovação.'}/>}</Card>}
  {tab==='Anexos'&&<Card>{detail.data?.attachments.length?<div className="grid gap-3">{detail.data.attachments.map((item,index)=><div key={index} className="rounded-lg border border-slate-200 p-4 text-sm font-medium">{String(item.originalName??'Arquivo')}</div>)}</div>:<Empty title="Anexos" text="O armazenamento binário aguarda a política de arquivos. Metadados existentes serão exibidos aqui."/>}</Card>}
  {tab==='Observações'&&<Card><div className="grid gap-5"><Select label="Centro de Custo" items={costCenters.data} registration={register('costCenterId')}/><label className="grid gap-1.5 text-sm font-medium">Observações<textarea rows={6} className="rounded-lg border border-slate-300 p-3" {...register('notes')}/></label><label className="flex items-center gap-3 text-sm font-medium"><input type="checkbox" className="size-4 accent-teal-700" {...register('draft')}/>Salvar como rascunho</label></div></Card>}
  {mutation.error&&!(mutation.error instanceof ApiError&&mutation.error.code==='POSSIBLE_DUPLICATE')&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{mutation.error instanceof ApiError?mutation.error.message:'Não foi possível salvar o título.'}</p>}
  {duplicatePayload&&<div className="fixed inset-0 z-30 grid place-items-center bg-slate-950/60 p-4"><div role="alertdialog" aria-modal="true" className="max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-bold">Possível duplicidade</h2><p className="mt-3 text-sm leading-6 text-slate-600">Já existe um título com o mesmo fornecedor, documento e série. Revise os dados ou confirme conscientemente a continuidade.</p><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={()=>setDuplicatePayload(undefined)}>Revisar</Button><Button onClick={()=>mutation.mutate({values:duplicatePayload,confirmed:true})}>Confirmar e salvar</Button></div></div></div>}
  </form>;
}

function Select({label,items,registration,required=false}:{label:string;items:Lookup[]|undefined;registration:ReturnType<typeof useForm<Values>>['register'] extends (...args:never[])=>infer R?R:never;required?:boolean}):ReactElement{return <label className="grid gap-1.5 text-sm font-medium">{label}<select className={inputClass} aria-required={required} {...registration}><option value="">Selecione</option>{items?.map(item=><option key={item.id} value={item.id}>{optionLabel(item)}</option>)}</select></label>;}
function Empty({title,text}:{title:string;text:string}):ReactElement{return <div className="py-12 text-center"><h2 className="font-bold">{title}</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-600">{text}</p></div>;}
