export interface FieldConfig { name:string;label:string;type?:'text'|'email'|'number'|'checkbox'|'select';required?:boolean;options?:readonly {value:string;label:string}[];lookup?:{path:string;value:string;label:string};placeholder?:string;inputMode?:'text'|'email'|'numeric'|'tel';mask?:'supplierDocument'|'phone';maxLength?:number;helperText?:string }
export interface ResourceColumnConfig { key:string;label:string;format?:'supplierDocument'|'phone'|'supplierType'|'activeStatus' }
export interface ResourceConfig { path:string;title:string;description:string;singular:string;columns:readonly ResourceColumnConfig[];fields:readonly FieldConfig[] }
const active={key:'isActive',label:'Situação',format:'activeStatus'} as const;const codeName=[{key:'code',label:'Código'},{key:'name',label:'Nome'},active] as const;
export const resources:Record<string,ResourceConfig>={
  suppliers:{path:'/suppliers',title:'Fornecedores',description:'Pessoas físicas, jurídicas e fornecedores estrangeiros.',singular:'Fornecedor',columns:[{key:'legalName',label:'Razão social / Nome'},{key:'documentNumber',label:'Documento',format:'supplierDocument'},{key:'phone',label:'Telefone',format:'phone'},{key:'supplierType',label:'Tipo',format:'supplierType'},active],fields:[{name:'supplierType',label:'Tipo',type:'select',required:true,options:[{value:'COMPANY',label:'Pessoa jurídica'},{value:'INDIVIDUAL',label:'Pessoa física'},{value:'FOREIGN',label:'Estrangeiro'}]},{name:'legalName',label:'Razão social / Nome',required:true},{name:'tradeName',label:'Nome fantasia'},{name:'documentNumber',label:'CPF / CNPJ / Documento',mask:'supplierDocument',maxLength:18,helperText:'Pessoa física usa CPF, jurídica usa CNPJ e estrangeiro aceita documento livre.'},{name:'countryCode',label:'País',placeholder:'BR',maxLength:2},{name:'email',label:'E-mail',type:'email',inputMode:'email',helperText:'Informe um e-mail válido para contato.'},{name:'phone',label:'Telefone',mask:'phone',inputMode:'tel',maxLength:15},{name:'mobilePhone',label:'Celular',mask:'phone',inputMode:'tel',maxLength:15},{name:'secondaryPhone',label:'Telefone adicional',mask:'phone',inputMode:'tel',maxLength:15},{name:'representativeName',label:'Representante',helperText:'No modelo atual, este campo é apenas o nome do representante.'},{name:'isApproved',label:'Aprovado',type:'checkbox'},{name:'isBlocked',label:'Bloqueado',type:'checkbox'},{name:'isActive',label:'Ativo',type:'checkbox'}]},
  'financial-categories':{path:'/financial-categories',title:'Categorias financeiras',description:'Classificação hierárquica das despesas.',singular:'Categoria',columns:codeName,fields:[{name:'code',label:'Código',required:true},{name:'name',label:'Nome',required:true},{name:'natureCode',label:'Natureza',type:'select',options:[{value:'EXPENSE',label:'Despesa'},{value:'REVENUE',label:'Receita'}]},{name:'parentId',label:'Categoria superior',type:'select',lookup:{path:'/financial-categories',value:'id',label:'name'}},{name:'isActive',label:'Ativa',type:'checkbox'}]},
  'cost-centers':{path:'/cost-centers',title:'Centros de custo',description:'Estrutura de alocação gerencial.',singular:'Centro de custo',columns:codeName,fields:[{name:'code',label:'Código',required:true},{name:'name',label:'Nome',required:true},{name:'parentId',label:'Centro superior',type:'select',lookup:{path:'/cost-centers',value:'id',label:'name'}},{name:'isActive',label:'Ativo',type:'checkbox'}]},
  'document-types':{path:'/document-types',title:'Tipos de documento',description:'Documentos aceitos nos lançamentos.',singular:'Tipo de documento',columns:codeName,fields:[{name:'code',label:'Código',required:true},{name:'name',label:'Nome',required:true},{name:'requiresFiscalKey',label:'Exige chave fiscal',type:'checkbox'},{name:'isActive',label:'Ativo',type:'checkbox'}]},
  'payment-methods':{path:'/payment-methods',title:'Formas de pagamento',description:'Meios previstos para liquidação.',singular:'Forma de pagamento',columns:codeName,fields:[{name:'code',label:'Código',required:true},{name:'name',label:'Nome',required:true},{name:'isActive',label:'Ativa',type:'checkbox'}]},
  'payment-terms':{path:'/payment-terms',title:'Condições de pagamento',description:'Prazos e parcelamentos comerciais.',singular:'Condição de pagamento',columns:codeName,fields:[{name:'code',label:'Código',required:true},{name:'name',label:'Nome',required:true},{name:'installmentCount',label:'Quantidade de parcelas',type:'number'},{name:'intervalDays',label:'Intervalo em dias',type:'number'},{name:'isActive',label:'Ativa',type:'checkbox'}]},
  banks:{path:'/banks',title:'Bancos',description:'Instituições financeiras utilizadas pela tesouraria.',singular:'Banco',columns:codeName,fields:[{name:'code',label:'Código bancário',required:true},{name:'name',label:'Nome',required:true},{name:'isActive',label:'Ativo',type:'checkbox'}]},
  'bank-accounts':{path:'/bank-accounts',title:'Contas bancárias',description:'Contas utilizadas na programação e nos pagamentos.',singular:'Conta bancária',columns:[{key:'accountName',label:'Nome da conta'},{key:'branchNumber',label:'Agência'},{key:'accountNumber',label:'Conta'},active],fields:[{name:'bankId',label:'Banco',type:'select',required:true,lookup:{path:'/banks',value:'id',label:'name'}},{name:'accountName',label:'Nome da conta',required:true},{name:'branchNumber',label:'Agência'},{name:'accountNumber',label:'Número da conta',required:true},{name:'accountType',label:'Tipo',type:'select',options:[{value:'CHECKING',label:'Conta corrente'},{value:'SAVINGS',label:'Poupança'},{value:'PAYMENT',label:'Conta de pagamento'}]},{name:'pixKey',label:'Chave PIX'},{name:'isDefault',label:'Conta padrão',type:'checkbox'},{name:'isActive',label:'Ativa',type:'checkbox'}]},
};
