import { useQuery } from '@tanstack/react-query';
import { useState, type ReactElement } from 'react';
import { Link } from 'react-router-dom';
import { httpClient } from '../api/http-client';
import { Card } from '../components/ui/card';
import { currency } from '../payables/payables-types';
import { monthRange, shortDate, type DashboardResponse, type OptionResponse } from '../intelligence/contracts';

const highlight={OVERDUE:'border-red-200 bg-red-50 text-red-800',TODAY:'border-amber-200 bg-amber-50 text-amber-800',UPCOMING:'border-sky-200 bg-sky-50 text-sky-800'} as const;
export function FoundationPage():ReactElement{
  const initial=monthRange();const [from,setFrom]=useState(initial.from);const [to,setTo]=useState(initial.to);const [supplierId,setSupplier]=useState('');const [categoryId,setCategory]=useState('');
  const query=useQuery({queryKey:['dashboard',from,to,supplierId,categoryId],queryFn:async()=>(await httpClient.get<DashboardResponse>('/api/v1/dashboard',{params:{from,to,supplierId:supplierId||undefined,categoryId:categoryId||undefined}})).data});
  const suppliers=useQuery({queryKey:['dashboard-suppliers'],queryFn:async()=>(await httpClient.get<OptionResponse>('/api/v1/suppliers',{params:{pageSize:100,active:true}})).data.data});
  const categories=useQuery({queryKey:['dashboard-categories'],queryFn:async()=>(await httpClient.get<OptionResponse>('/api/v1/financial-categories',{params:{pageSize:100,active:true}})).data.data});
  const summary=query.data?.summary;const maximum=Math.max(1,...(query.data?.categories??[]).map(item=>Number(item.amount)));
  return <div className="grid gap-6"><header><p className="text-sm font-bold uppercase tracking-widest text-teal-700">Inteligência financeira</p><h1 className="mt-1 text-3xl font-bold">Visão geral</h1><p className="mt-2 text-slate-600">Saldos, pagamentos e compromissos do período.</p></header>
    <Card><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label className="grid gap-1 text-sm font-semibold">De<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="min-h-10 rounded-lg border border-slate-300 px-3"/></label><label className="grid gap-1 text-sm font-semibold">Até<input type="date" value={to} onChange={e=>setTo(e.target.value)} className="min-h-10 rounded-lg border border-slate-300 px-3"/></label><label className="grid gap-1 text-sm font-semibold">Fornecedor<select value={supplierId} onChange={e=>setSupplier(e.target.value)} className="min-h-10 rounded-lg border border-slate-300 bg-white px-3"><option value="">Todos</option>{suppliers.data?.map(item=><option key={item.id} value={item.id}>{item.legalName}</option>)}</select></label><label className="grid gap-1 text-sm font-semibold">Categoria<select value={categoryId} onChange={e=>setCategory(e.target.value)} className="min-h-10 rounded-lg border border-slate-300 bg-white px-3"><option value="">Todas</option>{categories.data?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div></Card>
    {query.isError?<Card><p role="alert" className="text-red-700">Não foi possível carregar o dashboard.</p></Card>:<><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{([['Total a pagar',summary?.totalPayable,'text-slate-950'],['Vencidos',summary?.overdue,'text-red-700'],['A vencer',summary?.upcoming,'text-sky-700'],['Pagos',summary?.paid,'text-emerald-700']] as const).map(([label,value,color])=><Card key={label}><p className="text-sm font-semibold text-slate-500">{label}</p><p className={`mt-3 text-2xl font-black ${color}`}>{query.isLoading?'—':currency(value??0)}</p><p className="mt-1 text-xs text-slate-400">No período selecionado</p></Card>)}</section>
    <section className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><Card><h2 className="text-lg font-bold">Saldo por categoria</h2><div className="mt-6 grid gap-4">{query.data?.categories.map(item=><div key={item.label}><div className="mb-1 flex justify-between gap-4 text-sm"><span>{item.label}</span><strong>{currency(item.amount)}</strong></div><div className="h-2.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-600" style={{width:`${Math.max(3,Number(item.amount)/maximum*100)}%`}}/></div></div>)}{query.data?.categories.length===0&&<p className="py-10 text-center text-slate-500">Sem valores no período.</p>}</div></Card><Card><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Próximos compromissos</h2><Link to="/agenda" className="text-sm font-bold text-teal-700">Ver agenda →</Link></div><div className="mt-4 grid gap-2">{query.data?.upcoming.map(item=><Link to={`/payables/${item.id}`} key={`${item.id}-${item.dueDate}`} className={`grid grid-cols-[56px_1fr_auto] items-center gap-3 rounded-lg border p-3 ${highlight[item.highlight]}`}><span className="text-xs font-black uppercase">{shortDate(item.dueDate)}</span><span className="min-w-0"><span className="block truncate text-sm font-bold">{item.supplierName}</span><span className="text-xs">Doc. {item.documentNumber}</span></span><strong className="text-sm">{currency(item.openBalance)}</strong></Link>)}{query.data?.upcoming.length===0&&<p className="py-10 text-center text-slate-500">Nenhum compromisso no período.</p>}</div></Card></section></>}</div>;
}
